# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
  - title: "🚀 Website"
    labels:
      - "website"
  - title: "📚 Governance"
    labels:
      - "governance"
